/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/dashboard/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login with email + password */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            email: string;
            password: string;
          };
        };
      };
      responses: {
        200: components['responses']['LoginResponse'];
        401: components['responses']['UnauthorizedError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/v1/payments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List of payments */
    get: {
      parameters: {
        query?: {
          /** @description Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc) */
          sort?: components['parameters']['sort'];
          /** @description status of payment (completed , processing , or failed) */
          status?: string;
          /** @description payment id */
          id?: string;
          /** @description Page number (1-based) */
          page?: number;
          /** @description Number of payments per page */
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['PaymentListResponse'];
        401: components['responses']['UnauthorizedError'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /** @example 401 */
      code: number;
      /** @example Unauthenticated: missing or invalid token */
      message: string;
    };
    User: {
      email?: string;
      role?: string;
      token?: string;
    };
    Payment: {
      /** @example 1 */
      id?: string;
      /** @example Merchant A */
      merchant_name?: string;
      /**
       * @example completed
       * @enum {string}
       */
      status?: 'completed' | 'processing' | 'failed';
      /** @example 250000 */
      amount?: number;
      /** Format: date-time */
      created_at?: string;
    };
    /** @description Aggregate statistics across all matching payments (not just the current page) */
    Summary: {
      /** @description Total number of payments matching the filter */
      total?: number;
      completed?: number;
      processing?: number;
      failed?: number;
      /** @description Sum of all payment amounts matching the filter */
      total_amount?: number;
    };
  };
  responses: {
    /** @description return token and user information */
    LoginResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['User'];
      };
    };
    /** @description Payment List */
    PaymentListResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          payments?: components['schemas']['Payment'][];
          /** @description Total number of payments matching the filter */
          total?: number;
          /** @description Current page number (1-based) */
          page?: number;
          /** @description Number of payments per page */
          limit?: number;
          /** @description Total number of pages */
          total_pages?: number;
          summary?: components['schemas']['Summary'];
        };
      };
    };
    /** @description Authentication failed or missing credentials */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    /** @description Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc) */
    sort: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
